import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import "tippy.js/dist/tippy.css";
import { Transition } from "@headlessui/react";
import { useState } from "react";

const Home: NextPage = () => {
  const [isShowing, setIsShowing] = useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Transition
        show={isShowing}
        enter="transition-opacity duration-75"
        enterFrom="opacity-0"
        enterTo="opacity-100"
        leave="transition-opacity duration-150"
        leaveFrom="opacity-100"
        leaveTo="opacity-0"
      >
        I will fade in and out
      </Transition>
    </div>
  );
};

export default Home;
